// nuxt-appkit/components/ThemeToggle.vue
<template>
  <button
    class="theme-toggle"
    aria-label="Toggle theme"
    @click="toggle"
  >
    <svg class="icon-sun" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
      <path stroke-linecap="round" stroke-linejoin="round" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
    </svg>
    <svg class="icon-moon" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
      <path stroke-linecap="round" stroke-linejoin="round" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
    </svg>
  </button>
</template>

<script setup lang="ts">
function toggle() {
  const isDark = document.documentElement.dataset.theme !== 'light';
  const theme = isDark ? 'light' : 'dark';

  document.documentElement.dataset.theme = theme;

  // Dispatch event for Swap component and AppKit to pick up the theme change
  window.dispatchEvent(new CustomEvent('theme-change', { detail: { theme } }));
}
</script>

// react/app/components/ThemeToggle.tsx
"use client";

import { useCallback } from "react";

export function ThemeToggle() {
  const toggle = useCallback(() => {
    const isDark = document.documentElement.dataset.theme !== "light";
    const theme = isDark ? "light" : "dark";

    document.documentElement.dataset.theme = theme;
    document.getElementById("swap-widget")?.setAttribute("theme", theme);

    // Dispatch event for AppKit to pick up theme change
    window.dispatchEvent(new CustomEvent('theme-change', { detail: { theme } }));
  }, []);

  return (
    <button className="theme-toggle" aria-label="Toggle theme" onClick={toggle}>
      <svg className="icon-sun" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
      </svg>
      <svg className="icon-moon" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
      </svg>
    </button>
  );
}
