// vue-ethers/src/components/LocaleSelect.vue
<template>
  <select class="nav-select" aria-label="Language" @change="onChange">
    <option v-for="locale in SUPPORTED_LOCALES" :key="locale.value" :value="locale.value">
      {{ locale.label }}
    </option>
  </select>
</template>

<script setup lang="ts">
import { SUPPORTED_LOCALES } from '@/constants';

function onChange(e: Event) {
  const target = e.target;
  if (!(target instanceof HTMLSelectElement)) return;
  window.dispatchEvent(new CustomEvent('locale-change', { detail: { locale: target.value } }));
}
</script>

// next-rainbowkit/app/components/LocaleSelect.tsx
"use client";

import { useLocale } from "../context/locale";

export function LocaleSelect() {
  const { locale, setLocale } = useLocale();

  return (
    <select
      className="locale-select"
      aria-label="Language"
      value={locale}
      onChange={(e) => setLocale(e.target.value)}
    >
      <option value="en-US">EN</option>
      <option value="zh-CN">中文</option>
      <option value="zh-TW">繁體</option>
      <option value="ja-JP">日本語</option>
      <option value="ko-KR">한국어</option>
    </select>
  );
}
